# Generated by Django 4.1.3 on 2023-01-29 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='', upload_to='static/uploads/%Y-%m-%d %H:%M:%S'),
        ),
    ]
