# Generated by Django 4.1.3 on 2023-02-07 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('programming', 'Programming'), ('game', 'game'), ('network', 'network'), ('linux', 'linux'), ('android', 'android'), ('graphic', 'graphic')], default='', max_length=50),
        ),
    ]
